import { NextRequest, NextResponse } from "next/server";

const FOXIT_CLIENT_ID = process.env.FOXIT_CLIENT_ID || "";
const FOXIT_CLIENT_SECRET = process.env.FOXIT_CLIENT_SECRET || "";
const FOXIT_PDF_CLIENT_ID = process.env.FOXIT_PDF_CLIENT_ID || "";
const FOXIT_PDF_CLIENT_SECRET = process.env.FOXIT_PDF_CLIENT_SECRET || "";
const FOXIT_BASE_URL = "https://developer-api.foxit.com";

/**
 * Foxit Integration - Incident PDF Report Generation
 * Uses Foxit Document Generation API + PDF Services API
 * Hackathon: DeveloperWeek 2026
 */

// Minimal DOCX template as base64 - a simple Word XML structure
// In production this would be a real .docx file uploaded to storage
function buildDocxTemplateBase64(): string {
  // This is a minimal valid DOCX XML structure with Foxit merge tokens
  // Foxit uses [[token]] syntax for merge fields
  const wordXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p><w:r><w:t>INCIDENT REPORT</w:t></w:r></w:p>
    <w:p><w:r><w:t>ID: [[incident_id]]</w:t></w:r></w:p>
    <w:p><w:r><w:t>Title: [[title]]</w:t></w:r></w:p>
    <w:p><w:r><w:t>Status: [[status]]</w:t></w:r></w:p>
    <w:p><w:r><w:t>Date: [[created_at]]</w:t></w:r></w:p>
    <w:p><w:r><w:t>Root Cause: [[root_cause]]</w:t></w:r></w:p>
    <w:p><w:r><w:t>Fix Steps: [[fix_steps]]</w:t></w:r></w:p>
    <w:p><w:r><w:t>Confidence: [[confidence]]</w:t></w:r></w:p>
    <w:p><w:r><w:t>Generated by Autonomous Incident Agent (AIA)</w:t></w:r></w:p>
  </w:body>
</w:document>`;

  return Buffer.from(wordXml).toString("base64");
}

async function foxitGeneratePdf(incident: any): Promise<ArrayBuffer> {
  const templateBase64 = buildDocxTemplateBase64();

  const mergeData = {
    incident_id: incident.id || "N/A",
    title: incident.title || "Untitled Incident",
    status: incident.status || "unknown",
    created_at: incident.created_at
      ? new Date(incident.created_at).toLocaleString()
      : new Date().toLocaleString(),
    root_cause:
      incident.autopsy?.root_cause_text ||
      incident.root_cause ||
      "Analyzing...",
    fix_steps: incident.autopsy?.manual_steps?.join("; ") || "See full report",
    confidence: incident.autopsy?.confidence
      ? `${(incident.autopsy.confidence * 100).toFixed(0)}%`
      : "N/A",
  };

  // Step 1: Generate document using Foxit Document Generation API
  const generateRes = await fetch(
    `${FOXIT_BASE_URL}/document-generation/api/GenerateDocumentBase64`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        client_id: FOXIT_CLIENT_ID,
        client_secret: FOXIT_CLIENT_SECRET,
      },
      body: JSON.stringify({
        base64FileString: templateBase64,
        outputType: "pdf",
        mergeData: { data: [mergeData] },
      }),
    },
  );

  if (!generateRes.ok) {
    const err = await generateRes.text();
    throw new Error(
      `Foxit Document Generation failed: ${generateRes.status} - ${err}`,
    );
  }

  const generateData = await generateRes.json();
  const pdfBase64: string =
    generateData.data?.base64FileString || generateData.base64FileString;

  if (!pdfBase64) {
    throw new Error("Foxit returned no PDF data");
  }

  // Step 2: Process with Foxit PDF Services API (add watermark)
  const processRes = await fetch(
    `${FOXIT_BASE_URL}/pdf-services/api/AddWatermark`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        client_id: FOXIT_PDF_CLIENT_ID || FOXIT_CLIENT_ID,
        client_secret: FOXIT_PDF_CLIENT_SECRET || FOXIT_CLIENT_SECRET,
      },
      body: JSON.stringify({
        base64FileString: pdfBase64,
        watermark: {
          text: "AIA - Autonomous Incident Agent",
          opacity: 20,
          rotation: -45,
        },
      }),
    },
  );

  if (processRes.ok) {
    const processData = await processRes.json();
    const finalBase64 =
      processData.data?.base64FileString ||
      processData.base64FileString ||
      pdfBase64;
    return Buffer.from(finalBase64, "base64").buffer;
  }

  return Buffer.from(pdfBase64, "base64").buffer;
}

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } },
) {
  const { id } = params;

  if (!FOXIT_CLIENT_ID || !FOXIT_CLIENT_SECRET) {
    return NextResponse.json(
      {
        error: "Foxit credentials not configured",
        setup:
          "Add FOXIT_CLIENT_ID and FOXIT_CLIENT_SECRET to environment variables",
        signup: "https://developer-api.foxit.com/",
      },
      { status: 503 },
    );
  }

  try {
    // Fetch incident from state service
    const STATE_URL = process.env.STATE_SERVICE_URL || "http://localhost:3002";
    let incident: any = { id, title: `Incident ${id}`, status: "unknown" };

    try {
      const stateRes = await fetch(`${STATE_URL}/incidents/${id}`);
      if (stateRes.ok) {
        incident = await stateRes.json();
      }
    } catch {
      // Use minimal incident data if state service unavailable
    }

    const pdfBuffer = await foxitGeneratePdf(incident);

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="incident-${id}-report.pdf"`,
        "Content-Length": pdfBuffer.byteLength.toString(),
        "X-Generated-By": "Foxit Document Generation API + PDF Services API",
      },
    });
  } catch (error: any) {
    console.error("[Foxit] PDF generation error:", error);
    return NextResponse.json(
      { error: error.message, service: "foxit-integration" },
      { status: 500 },
    );
  }
}

// Health check / info endpoint
export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));

  if (!FOXIT_CLIENT_ID || !FOXIT_CLIENT_SECRET) {
    return NextResponse.json({
      service: "foxit-integration",
      status: "credentials_missing",
      message: "Add FOXIT_CLIENT_ID and FOXIT_CLIENT_SECRET",
      signup_url: "https://developer-api.foxit.com/",
    });
  }

  try {
    const incident = body.incident || {
      id: "test-001",
      title: "Test Incident",
      status: "resolved",
      created_at: new Date().toISOString(),
      autopsy: {
        root_cause_text: "Test root cause",
        manual_steps: ["Step 1", "Step 2"],
        confidence: 0.95,
      },
    };

    const pdfBuffer = await foxitGeneratePdf(incident);

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="test-report.pdf"`,
        "X-Generated-By": "Foxit Document Generation API + PDF Services API",
      },
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
