export const docsRoutes = [
  { title: "Getting Started", href: "/getting-started" },
  { title: "Architecture Overview", href: "/architecture/overview" },
  { title: "Data Flow", href: "/architecture/data-flow" },
  { title: "AI Engine", href: "/architecture/ai-engine" },
  { title: "R2 Lifecycle", href: "/architecture/r2-lifecycle" },
  { title: "Git Integration", href: "/architecture/git-integration" },
  { title: "Repro Pipeline", href: "/architecture/repro-pipeline" },
  { title: "Config Reference", href: "/reference/config" },
  { title: "Event Schema", href: "/reference/events" },
  { title: "R2 Layout", href: "/reference/r2-layout" },
  { title: "State Schema", href: "/reference/state" },
  { title: "CLI Reference", href: "/reference/cli" },
  { title: "Node.js Tutorial", href: "/tutorials/node" },
  { title: "Next.js Tutorial", href: "/tutorials/next" },
  { title: "Vercel Tutorial", href: "/tutorials/vercel" },
  { title: "Netlify Tutorial", href: "/tutorials/netlify" },
  { title: "Debugging Guide", href: "/tutorials/debug" },
  { title: "Installation", href: "/install" },
  { title: "OpenTelemetry", href: "/opentelemetry" },
  { title: "R2 Setup", href: "/r2-setup" },
  { title: "GitHub Bot", href: "/github-bot" },
  { title: "Running Agent", href: "/running-agent" },
  { title: "Troubleshooting", href: "/troubleshooting" },
];
