import type { AiReasoningRequest, AiReasoningResponse } from "@repo/types";

export class YouComReasoner {
    constructor(private apiKey: string, private model: string) { }

    async analyze(req: AiReasoningRequest): Promise<AiReasoningResponse> {
        if (!this.apiKey || this.apiKey === "PLACEHOLDER") {
            console.warn("No You.com API key provided. Returning mock AI response.");
            return this.mockResponse(req);
        }

        const contextStr = req.file_context.map(f => `File: ${f.path}\nContent:\n${f.content}`).join("\n---\n");
        const prompt = `
You are an expert software engineer. Analyze the following stacktrace and code context to identify the root cause of the error.
Error Message: ${req.error_message}
Stacktrace:
${req.stacktrace}

Code Context:
${contextStr}

Task:
1. Explain the root cause concisely.
2. Provide a unified diff patch to fix the issue. The path in the diff should match the file path provided.
3. Provide a deterministic test case (TypeScript) to reproduce and verify the fix.
4. Estimate confidence score (0-1).

Output JSON only:
{
  "root_cause": "string",
  "patch": { "file_path": "string", "diff": "string" },
  "test_code": "string",
  "confidence": number
}
`;

        try {
            const response = await fetch("https://api.you.com/api/v1/chat", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-Queue-ID": this.apiKey
                },
                body: JSON.stringify({
                    message: prompt,
                    model: this.model
                })
            });

            if (!response.ok) {
                throw new Error(`You.com API Error: ${response.statusText}`);
            }

            const data = await response.json();

            const textFn = (data as any).generated_text || "";
            const jsonMatch = textFn.match(/\{[\s\S]*\}/);
            if (jsonMatch) {
                return JSON.parse(jsonMatch[0]);
            }
            throw new Error("Could not parse JSON from AI response");

        } catch (e) {
            console.error("AI Reasoner failed:", e);
            return this.mockResponse(req);
        }
    }

    private mockResponse(req: AiReasoningRequest): AiReasoningResponse {
        return {
            root_cause: "AI (Mock): Detected 'seeded_error' or 'cause_crash' logic. The application intentionally throws an error.",
            patch: {
                file_path: req.file_context[0]?.path || "unknown",
                diff: req.file_context[0]?.path ? `--- ${req.file_context[0].path}\n+++ ${req.file_context[0].path}\n@@ -1,1 +1,1 @@\n-// Fixed by AI\n` : ""
            },
            confidence: 0.85,
            test_code: "// Test generated by AI (Mock)"
        };
    }
}
