import type { AiReasoningRequest, AiReasoningResponse } from "@repo/types";

export class YouComReasoner {
  constructor(
    private apiKey: string,
    private model: string,
  ) {}

  async analyze(req: AiReasoningRequest): Promise<AiReasoningResponse> {
    if (
      !this.apiKey ||
      this.apiKey === "PLACEHOLDER" ||
      this.apiKey === "mock-key" ||
      this.apiKey === "mock"
    ) {
      console.warn("No You.com API key provided. Returning mock AI response.");
      return this.mockResponse(req);
    }

    const contextStr = req.file_context
      .map((f) => `File: ${f.path}\nContent:\n${f.content}`)
      .join("\n---\n");
    const prompt = `
You are an expert software engineer. Analyze the following stacktrace and code context to identify the root cause of the error.
Error Message: ${req.error_message}
Stacktrace:
${req.stacktrace}

Code Context:
${contextStr}

Task:
1. Explain the root cause concisely.
2. Provide a valid Unified Diff patch to fix the issue.
   - The patch MUST start with '--- a/{file_path}' and '+++ b/{file_path}'.
   - The file path in the diff must match exactly: ${req.file_context[0]?.path || "unknown"}.
   - Include at least 4-5 lines of context (unchanged lines) around the changes.
   - Ensure typical git diff header format (@@ -start,count +start,count @@).
3. Provide a deterministic test case (TypeScript) to reproduce and verify the fix.
4. Estimate confidence score (0-1).

Output JSON only:
{
  "root_cause": "string",
  "patch": { "file_path": "${req.file_context[0]?.path || "string"}", "diff": "string (multiline diff)" },
  "test_code": "string",
  "confidence": number
}
`;

    try {
      const response = await fetch("https://api.you.com/v1/agents/runs", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-API-Key": this.apiKey,
        },
        body: JSON.stringify({
          input: prompt,
          agent: "express",
        }),
      });

      if (!response.ok) {
        const errText = await response.text();
        throw new Error(
          `You.com API Error: ${response.status} ${response.statusText} - ${errText}`,
        );
      }

      const data = (await response.json()) as any;

      let textFn = "";
      if (data.output && Array.isArray(data.output)) {
        const answer = data.output.find(
          (o: any) => o.type === "message.answer",
        );
        if (answer) {
          textFn = answer.text;
        }
      }

      if (!textFn) {
        throw new Error("No answer text found in You.com response");
      }

      const jsonMatch = textFn.match(/\{[\s\S]*\}/);
      const codeBlockMatch = textFn.match(/```json\n([\s\S]*?)\n```/);

      if (codeBlockMatch) {
        return JSON.parse(codeBlockMatch[1]);
      }

      if (jsonMatch) {
        return JSON.parse(jsonMatch[0]);
      }

      console.warn(
        "Could not find JSON in AI response, attempting to parse full text if valid",
      );
      try {
        return JSON.parse(textFn);
      } catch (e) {
        throw new Error(
          `Could not parse JSON from AI response: ${textFn.substring(0, 100)}...`,
        );
      }
    } catch (e) {
      console.error("AI Reasoner failed:", e);
      return this.mockResponse(req);
    }
  }

  private mockResponse(req: AiReasoningRequest): AiReasoningResponse {
    return {
      root_cause:
        "AI (Mock): Detected 'seeded_error' or 'cause_crash' logic. The application intentionally throws an error.",
      patch: {
        file_path: req.file_context[0]?.path || "unknown",
        diff: req.file_context[0]?.path
          ? `--- ${req.file_context[0].path}\n+++ ${req.file_context[0].path}\n@@ -1,1 +1,1 @@\n-// Fixed by AI\n`
          : "",
      },
      confidence: 0.85,
      test_code: "// Test generated by AI (Mock)",
    };
  }
}
